# Taskwarrior Notifications Config
poll_interval: 30s  # How often to poll Taskwarrior (e.g., 30s, 1m)
notification_service: ntfy
ntfy:
  url: "https://ntfy.sh"
  topic: "task-herald"
  token: ""
shoutrrr:
  # List of Shoutrrr notification URLs, e.g. "ntfy://topic?token=..."
  urls: []
web:
  listen: "127.0.0.1:8080"
  auth: false
